[package]
name = "rust-ips"
version = "0.1.0"
edition = "2021"
author = "Frederic Beaudet <fredericbeaudet@gmail.com>"

[dependencies]
clap = { version = "~4.1.5", features = ["derive"]}
beryllium = "~0.9.2"
